### ISSUE TITLE
Nested quotes bug caused by bad csv file

### ISSUE THREAD

**Issue by jgoodell-gsa** [GSA/CHRISUpdate#108]

**Comment by tsaunders-gsa** [comment]
Code has been merged into Dev.

Pull Request: https://github.com/GSA/CHRISUpdate/pull/109

**Comment by dlenz-gsa** [comment]
The above issue is still producing handled errors in the HR Links Summary e-mail, listing records containing nested quotes as "Invalid record from CSV file" in the HR_Error_Summary file. A solution must be developed to either remove or handle these issues so that records in HR Links files facing this issue are able to receive updates through the daily update process.
